[package]
name = "rouge_asset"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
bevy = "0.9.0"
serde = "1.0.152"
serde_dhall = "0.12.1"
